### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by jaredallard** [jaredallard/shinojs#2]
**TODO**: .... make this crap actually stable.

## Natural Language Processing stuff

* [x] Implement Natural Language Processing
  * [ ] Store training data somewhere
  * [ ] Implement feedback system
  * [x] Ignore classifications under a specific score
  * [ ] Research ways of positive / negative feedback without user interaction (sentiment?)
* [x] Sentiment Analysis
  * [ ] Max out scores to prevent spamming pos/neg 

## Framework

* [ ] Stabilize API.
* [x] Fix code repetition, and modernize the code base entirely.
* [ ] v3.1 (stable build)
* [x] Document how the new choice schema system works.
* [x] Get Code Climate maintainability up to an A
* [x] Support multiple services
